apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k8gyy45e9-go
  janus-idp.io/tekton: k8gyy45e9-go
  backstage.io/kubernetes-id: k8gyy45e9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k8gyy45e9-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
